### ISSUE TITLE
Pre-Alpha 4

### ISSUE THREAD

**Issue by Toma400** [Toma400/The_Isle_of_Ansur#105]
# Description
Pre-alpha 4 is planned to be November major update (aka 0.4 in IoA versioning) and focus on finishing modding management aspects of the game.
While this may seem strange to focus so heavily on it early (which means delaying real gameplay), this decision is motivated by the fact that huge chunk of how IoA works is moderated by the same systems that moderate mods - so without mod management system, even working on vanilla elements would be harder.

# Todo
- [x] Mod Management Menu (#50)
  - [x] Ability to disable mods
  - [x] Ability to move up/down mod order
  - [x] Ability to remove mod
  - [x] Showcasing errors through MMM GUI
  - [x] Zippacks list containing `*` for disabled mods and `!` for errored ones
- [x] Avatars for characters (#88)
  - [x] URL-based
  - [x] Statpack-based
  - [x] Showcasing avatar in loading menu
- [x] Statpack/BRPGS expansion
  - [x] #60
  - [x] #100
- [x] Utilities
  - [x] GUI Classes
    - [x] #103
  - [x] Continuing with removing `@Deprecated` functions and removing old code
  - [x] Adding text size change with resolution change
- [x] Fixes
  - [x] #104

**Comment by Toma400** [comment]
So basically I've reached that nice moment of November update being highly done. This means that we should:
- Aim on primarily work on December update features from now on
- For November update:
  - Test all new features and search for bugs
  - Fix all bugs we know/find
  - Perform small QoL changes, like tooltip addition (yet not added)

**Comment by Toma400** [comment]
So basically I've reached that nice moment of November update being highly done. This means that we should:
- Aim primarily to work on December update features from now on
- For November update:
  - Test all new features and search for bugs
  - Fix all bugs we know/find
  - Perform small QoL changes, like tooltip addition (yet not added)

Release of November update is planned to be in later half of the month, probably around 20th Nov.

**Comment by Toma400** [comment]
Moved statpack changes to BRPGS, to pre-alpha 5, for both compatibility reasons and because it doesn't really matter right now. This allows for easier `0.3 - 0.4+` compat without breaking anything, and also shuffles a bit more tasks into update where this will start to matter.

**Comment by Toma400** [comment]
I think ability to remove mod could be delayed further into pre-alpha 5/6, and maybe have additional option to download mod from URL which would either zip the mod from GitHub source, download release .zip from GH release pages, or do download from Nexus? Hard to say, but you know what I mean here.
I do think tho that including this may be overkill for the release.

**Comment by Toma400** [comment]
I'd say that for current pre-alpha 4 release, we are mostly done. I'd probably move tooltip a bit further to either pre-alpha 4b or 5/6 even, because implementing it is kinda hard without properly structured custom Image/Text objects and I'm hesitating on what to pick.

Rest of release time right now I should spend on either fixing bugs that I find/know, removing deprecations, and mostly - drawing avatars and locations, so November and December update have enough resources to be rolled out without shame.
This means:
- at least 24 avatars for all races and genders
- at least 2 location images (to test travel between locations)
- hopefully one "empty avatar" image to replace `skeletontonguedworld` placeholder image

Similarly to textual parts and currently poor statistics section, those doesn't need to be explicitly complete, but at least location ones should be, considering it's required to have images for locations (unlike avatars for races or full race selection from BRPGS).

**Comment by Toma400** [comment]
Issues taken from this one (will updated as new ones come):
- #108

**Comment by Toma400** [comment]
Not sure why I haven't closed that yet, but here we go ^^
