### ISSUE TITLE
Pre-Alpha 5

### ISSUE THREAD

**Issue by Toma400** [Toma400/The_Isle_of_Ansur#106]
# Description
Pre-alpha 5 is planned to be December major update (aka 0.5 in IoA versioning) and be first release to introduce actual gameplay, in form of location main menu and possibly few others.

# Todo
- [x] Save system
  - [x] Save verificator object (covers save files & mod versions)
  - [x] Inventory .yaml file
    - [x] Item system that is able to use stacked items
    - [x] Somehow this may work with #100? Also make that work with origins
  - [x] Patch for older versions
- [x] Other stuffs
  - [x] https://github.com/Toma400/The_Isle_of_Ansur/issues/112
- [x] Location menu
  - [x] Image loading from worldpack
  - [x] ~~Travelling (?)~~
- [x] Diary menu
  - [x] ~~Save/load from there~~
  - [x] Exit to menu

**Comment by Toma400** [comment]
Inventory plans for pre-alpha 5, updated on today's brainstorming. Those systems should be set in place for the release, all others can be pushed to 6 or 7:
- inventory should be .yaml file
  - .yaml versus folder are pretty equal, but
  - .yaml allows for `:` which are crucial for IDs, filenames not (and nesting in folders is bad idea)
  - .yaml allows for list structure, so it will be okay to duplicate non-stackable IDs
  - it is highly unlikely to make .yaml file so big that it lags the game - but if so, there's always a possibility to overhaul it later
- current scope is to make inventory file create and be able to recognise and set stackable items (two items added by far share that quality)
  - this allows for #100 to be built
  - it also skips the struggle with non-stackable ones, which will be concern of later updates
  - but it also does some work that was needed to introduce inventory with most game-breaking update
 
Inventory being viewable is not the goal of this release - it can be added as indev feature if there's enough time, but should not be critical by any means.

**Comment by Toma400** [comment]
Since all points are met, I consider this as finished. Remaining features from milestone will be judged separately ^^
