### ISSUE TITLE
Pre-Alpha 6

### ISSUE THREAD

**Issue by Toma400** [Toma400/The_Isle_of_Ansur#114]
# Description
Pre-alpha 6 is planned to be update slotted to March or April 2024. It'd flesh out features introduced in 0.5, such as items, and introduce player to new menus, like character and inventory.

# Todo
- [x] Travelling
  - Should be barebones and focus on getting requirements/costs right - visual aspect to be expanded in PA7
- [x] Save system
  - [x] Ability to save from diary menu
  - [x] Loading from save, not buffer (proper diffentiation and copying mechanics)
  - [x] ~~Settings for gamesave to allow "exit without save" (or other way around, hardcore always-saving as option)~~
- [x] Fixes
  - [x] #118
  - [x] #119

**Comment by Toma400** [comment]
`Settings for gamesave to allow "exit without save" (or other way around, hardcore always-saving as option)` requires patching, so I'd suggest shelving it to PA7 or listing all possible things you may want to add to save beforehand.
Like not only #60 (if it is decided to be static), but also things like weight, HP, MP, SP, needs and so on. Faction/guild reputation even. I do feel like this is massive and should be rather pushed for later, so if we were to break things, it wouldn't be right after breaking PA5 update (and making patch would make more sense, as it'd be one thing at once).

**Comment by Toma400** [comment]
Moving some features over to PA7 and PA8, just so it's easier for me to finish this update and have smaller pieces to go over later. Roadmap would need to be adjusted.

**Comment by Toma400** [comment]
Finished with bcabd51. ^^
