### ISSUE TITLE
Pre-Alpha 7

### ISSUE THREAD

**Issue by Toma400** [Toma400/The_Isle_of_Ansur#122]
# Description
Pre-alpha 7 is meant to be expansion of pre-alpha 6, but also implement inventory system as primary goal for the release.

# Todo
- [x] Time system
- [x] SP/HP/MP introduced?
  - [ ] Show them on character menu
  - [ ] TravelScript conditions and management
- [x] #127
- [ ] #128
- [ ] #121
- [x] QoL improvements
  - [x] #126
  - [x] Make loading menu more informing/better visually
- [ ] Items system
  - [ ] Overhaul inventory system and make game register and show it
  - [ ] Add/remove from inventory (from menu)
  - [ ] Add/remove from inventory (TravelScript) + conditions
  - [ ] Brainstorm final "wear/equip" slots
  - [ ] #130 
  - [ ] Optional
    - [ ] #56
    - [ ] Weight system implemented
      - [x] Calculate weight and set it in player's data
      - [ ] Have max weight limit
      - [ ] Make travel speed affected by exceeding weight limit?
    - [ ] `Bonus: book viewer`
      - [ ] #115
- [ ] Menus
  - [ ] Inventory menu
  - [x] Character menu
- [ ] Travelling Expansion
  - [ ] #125
    - [x] Allow for better script checking for values, so int/float/bool and string can be easily represented
    - [ ] Check for no key
  - [ ] Map-based destinations, with custom icons and all `stretch goal`
- [ ] Hardcore features
  - [x] Always save on exit option
- [ ] Fixes
  - [x] #124
  - [x] #129
  - [ ] #51
- [ ] Update .odt/.pdf documentation for modding (use .md files as context)

**Comment by Toma400** [comment]
Added some more travelling-related features, alongside inventory being now prioritised. Time, tiredness, inventory and expanded travelling scripting will make this pre-alpha 6 feature really be something in pre-alpha 7.
Instead of making small PA7 release and introduce most of this in PA8, this could be done in one go - but the deadline I'd assume will be December, as it's a lot of work.
