### ISSUE TITLE
Pre-Alpha 8

### ISSUE THREAD

**Issue by Toma400** [Toma400/The_Isle_of_Ansur#123]
# Description
Pre-alpha 8 is meant to improve on features introduced in previous versions.

# Todo
- [ ] Performance checks and improvements
- [ ] Proper location-based music
  - [ ] Check if menu music don't repeat in locations
  - [ ] Location should have music start related to location and specific time/conditions
- [x] Race/class survey with possibility to deprecate some of those temporarily
- [ ] Resupplying avatars and names for some races?
- [ ] #61 (how to make it work with current files?)
- [ ] Swapping location images if possible to CC0 ones
