### ISSUE TITLE
First milestone of pre-alpha 3 version

### ISSUE THREAD

**Issue by Toma400** [Toma400/The_Isle_of_Ansur#41]
During recent commits, it can be seen that more and more progress has been made and that first milestone of pre-alpha is going to be completed soon - as a lot of background work is done, and now most of things can be easily created by just implementing already added functions. 
Next milestone for pre-alpha 3 will be implementation of menu options (settings and pack management), and last milestone will introduce character creating, finishing pre-alpha 3 and porting over all things from terminal version to PyGame version.

Before first milestone is reached, though, there are several elements that need to be done:

- [x] Possibly switching `font` into `freefont`, as the latter seems to be more customisable, which is important for text-based game
- [x] Solving UTF-8 support (#38) - possibly previous point is the solution
- [x] Creating text which adjusts its size more precisely, and can be flexible, so PyGamed IoA can switch to translateable strings, as with previous release (as the same sentence in non-English will differ in length)
- [x] A way to return values from nested functions - so each `handler` in main loop can interfere with variables from the loop itself
- [x] Similarly to above, a way to healthily exit the program from said `handlers` - currently, exiting through `pygame.quit()` in **gui_handler** prints issue because it does check later handlers, yet without PyGame running
- [x] #42

**Comment by Toma400** [comment]
Finished first milestone! Ayyyy :3
