### ISSUE TITLE
Second milestone of pre-alpha 3 version

### ISSUE THREAD

**Issue by Toma400** [Toma400/The_Isle_of_Ansur#46]
After first milestone, second one seems to develop pretty rapidly. Hence, decided to make similar bulk topic for remaining goals and issues which should be done before milestone is reached.

**Feature-wise**
- [x] Adding settings menu with all its functionality
- [x] Adding resolution change (separated just because it may need additional time)
- [ ] Adding pack management menu with all its functionalities (#50)
- [ ] Expanding info.json features for mods (#50)

**Technical**
- [ ] Migration to object-oriented, outsourced system (`Image`, `Text`, `Listbox` objects put within `gui_objects`)
   - [ ] Migration of Image (incl. checks for all features)
   - [ ] Migration of Text (incl. check for all features)
      - [ ] Feature of outlining
   - [ ] Creation of Listbox (incl. check for all features)
- [x] Creating yet another, size-adjustable text renderer, this time taking start_pos and end_pos as arguments (#44)
- [x] Creating text renderer for longer strings, with end-of-line-collision recognition and breaker
- [x] Creating feature of scrolling through data, so you can manage mods (2nd milestone) and other aspects of the game (races/classes/avatars/inventory - 3nd milestone and later)
- [x] Text input (#67)
- [x] `Requests` feature checking versioning and notifying about new version of the game (probably you could also uncheck this feature in settings menu, if it gets annoying)

**Purely Technical**
- [ ] Finding font for Polish (& Hungarian) translations
- [ ] Possible issue with - https://github.com/Toma400/The_Isle_of_Ansur/blob/6b0c524d4f841b8b19c9503f956885b8c78d0416/core/graphics/text_manag.py - rect/text spacing in put_rectext
- [x] Issue #62

**Bugs**
- [ ] Issue #51
- [x] Issue #76
- [x] Issue #52 
- [x] Issue #47

**BCS**
- [ ] BCS 1.0

**2nd >> 3rd**
- [x] Character creation menu (either gray out, if not finished, or finish)

**Comment by Toma400** [comment]
Line breakers and scrolling can be possibly done with use of [pygame_gui module](https://github.com/MyreMylar/pygame_gui) suggested by the creator on Reddit. May be worth giving a go.

**Comment by Toma400** [comment]
To exclude possible overuse of loops in module management, I suggest doing it like that:

- At start of the game (module importing), the list of available mods and active mods is given - it is written into `_temp` folder in separate file
- Any further use will check this _temp file instead of importing those mods over again
- Only in case of bigger changes (such as module (de)activation, removal, whatever) this initial element will be reloaded, and it will run not constantly, but after player's interaction

**Comment by Toma400** [comment]
Would be good (though not obligatory) to create inputs in second milestone too, as this will be useful for second milestone.
If not done, just repost this comment under third milestone list.

Possibly useful resources:
- [StackOverflow Thread](https://stackoverflow.com/questions/46390231/how-can-i-create-a-text-input-box-with-pygame)

**Comment by Toma400** [comment]
Listboxes should use settings destined for them (#59)

**Comment by Toma400** [comment]
- [ ] Listboxes should use only one type of visualisation, being mixed version of current one. It should take specific number of entries (settings-based), but if it overexceedes entries available, it should shorten to the max of entries available.

So, for example, settings give "10" as requested value.
If list has 25 entries, it will have 3 pages - 1-10, 11-20, 21-25. It will scale itself automatically to fit 10 elements on the screen, and with last 21-25 it will just have half of the listbox empty.
But, if list has 5 entries, there's no need to leave half of listbox empty. In this case, there can be adjusting making those entries bigger enough to fill whole listbox.
This could be a thing to customise, if something, in settings, but making those two separate makes no sense, after my today's brainstorm. Both separate variants are limiting and too strict, and give little to no flexibility.

**Comment by Toma400** [comment]
`_temp/copy_of_path` storage for resized images changed to `_temp/img/copy_of_path`, for better flexibility. Will commit alongside listbox bulk commit.

There can be improvement needed for cases when there are two various-sized images used in one screen - if this system refers to the same image, only one resizement is used, making another one distorted.

**Comment by Toma400** [comment]
Not required, but would be amazing to have first BCS version out for this release. Obviously it would not be released for GitHub, as milestones do not, but would make it nicely bound together, and make it easier for third milestone to add features such as race and class making.

**Comment by Toma400** [comment]
Okay, so to conclude this last issue that should be organised out of existence, but has valuable stuff written.

---
Those below either are already, or migrate to MMM (#50)
> Adding pack management menu with all its functionalities
> Expanding info.json features for mods

Moved to other places:
> Possible issue with - https://github.com/Toma400/The_Isle_of_Ansur/blob/6b0c524d4f841b8b19c9503f956885b8c78d0416/core/graphics/text_manag.py - rect/text spacing in put_rectext

Moved to #89:
> Finding font for Polish (& Hungarian) translations

Moved to pre-alpha 4:
> Issue #51

Delayed:
> BCS

Things not listed there were also probably moved somewhere, where this is useful. Closing the topic, as pre-alpha 3 is finished and we don't need the bulk topic anymore.
