### ISSUE TITLE
BCS Todo

### ISSUE THREAD

**Issue by Toma400** [Toma400/The_Isle_of_Ansur#71]
This is short list of features that BCS should have, in its early and middle iterations.

**BASICS**
- [ ] Allow for adding/removing/managing projects
- [ ] Allow for choosing ID being worked on and `ansur` being protected (with different features)
- [ ] Allow for adding new panoramas & music, with `%PR` key available
- [ ] Export of mod into .zip file in `mods` directory, with generator adjusting outcome files to current implementation

**QOL FOR PROFESSIONAL PART**
- [ ] Export of mod into shareable file read by all BCS across (with elements/assets packaged)
- [ ] Merging of mods with possibility to resolve conflicts (#70)
- [ ] GitHub integration for projects files
- [ ] Linux and Android versions

**Comment by Toma400** [comment]
Naming convention:
``[major version].[minor version][fix version]``
Example:
``1.1b <- version 1, with some new features, bugfix released``

**Versioning:**
1.0 - pre-alpha phase (pre-BSaL cycle)
2.0 - alpha phase (BSaL-XD-DR cycle)
3.0 - beta phase (DotE-TSAP cycle)
4.0 - release phase (TDIC-BotW cycle)
5.0+ - any later phases/cycles

**Comment by Toma400** [comment]
As lovely as this list is, closing because of #28 being closed.
