### ISSUE TITLE
Pre-Alpha 3B

### ISSUE THREAD

**Issue by Toma400** [Toma400/The_Isle_of_Ansur#92]
This is bulk topic for pre-alpha 3b contents. This subversion is meant to be mostly bugfixing update, but also to focus on Polish translation.
---
Features:
- [x] Polish translation
  - [x] Find proper font (#89)

Issues:
- [x] #94 
- [x] #93

Improvements:
- Lore:
  - [x] Improved descriptions of races and classes
- Technical:
  - [x] Allowing for custom description key (#85)
  - [x] Changing "write your story" part of character creation, so it features only textbox
  - [x] Simple backpedaling in character creation by allowing to go back to previous option

Pre-alpha 4 preparation:
- [x] Adding unpacking of `packs` folder if autoimport is on (bringing back previous system & #29)
  - [x] `vanilla_modules` in system_ref.toml is used to not remove core pack (this should be changed eventually so vanilla will be overwriteable without issues)
- [x] Pack validation (#95, #97)
- [x] Other pack management-related features (#96)

**Comment by Toma400** [comment]
Custom description key is moved to pre-alpha 4, so I'm ticking it out despite it not being done.

**Comment by Toma400** [comment]
Closed today with release 🥰
